version: "3.8"
services:
  docker-postgres:
    image: postgres:16-bullseye
    container_name: postgres16_tasks
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p
      POSTGRES_DB: tasks
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_tasks
    restart: always
    ports:
      - "8888:80"

    networks:
      - default
    environment:
      PGADMIN_DEFAULT_EMAIL: iphonemarlon@gmail.com
      PGADMIN_DEFAULT_PASSWORD: p
    volumes:
      - pgadmin-data:/var/lib/pgadmin

 
volumes:
  local_pgdata:
  pgadmin-data:
  