import { ApiProperty } from "@nestjs/swagger";
import { Role } from "@prisma/client";
import { Ticket } from "src/ticket/entities/ticket.entity";
import { ObjectType, Field } from "@nestjs/graphql";
import { Type } from "class-transformer";
import { IsEmail, IsOptional, IsString, Matches, MaxLength, MinLength, NotContains, ValidateNested } from "class-validator";

@ObjectType()
export class User {
    @Field()
    @ApiProperty({
        description: "User Id, generated by uuid",
        nullable: false,
        required: true,
        type: "string",
        example: "2313w49-0db7-4v79-aacc-52624343bf2t",
    })
    id: string;
    
    @Field()
    @ApiProperty({
        description: "Name",
        nullable: false,
        required: true,
        type: "string",
        example: "John Sample",
    })
    name: string;

    @Field()
    @ApiProperty({
        description: "Email",
        uniqueItems: true,
        nullable: false,
        required: true,
        type: "string",
        example: "youremail@example.com",
    })
    email: string;
    // @Field()
    // @ApiProperty({
    //     description: "Email Verified",
    //     nullable: true,
    //     required: false,
    //     type: "string",
    //     example: "2022-01-01T00:00:00.000Z",
    // })
    // emailVerified?: string;
    
    @Field()
    @ApiProperty({
        description: "Password: Min 6 characters, 1 uppercase, 1 lowercase and 1 number",
        nullable: false,
        required: true,
        type: "string",
        example: "Password123",
    })
    password?: string;
    
   
    @ApiProperty({
        description: "Password: Min 6 characters, 1 uppercase, 1 lowercase and 1 number",
        nullable: false,
        required: true,
        type: "string",
        example: "Password123",
    })
    passwordconf?: string;
    
    @Field()
    @ApiProperty({
        description: "User Role (admin, user)",
        nullable: false,
        required: true,
        type: "string",
        example: "user",
    })
    role: Role;
    
   

 
    
    @Field()
    @ApiProperty({
        description: "Created At",
        nullable: true,
        required: false,
        type: "string",
        example: "2022-01-01T00:00:00.000Z",
    })    
    createdAt?: Date; 
    @Field()
    @ApiProperty({
        description: "Updated At",
        nullable: true,
        required: false,
        type: "string",
        example: "2022-01-01T00:00:00.000Z",
    })    
    updatedAt?: Date; 
    
   
    @ApiProperty({
        required: false,
        type: () => [Ticket],
      })
      @ValidateNested()
      @Type(() => Ticket)
      @IsOptional()
      tickets?: Array<Ticket>;
    
}



